Finance_news_aggregator/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("finance_app.urls")),
    path("users/", include("users.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('subscribe/', include('subscribe.urls')),
    path('retirement-calculator/', include('retirement_calculator.urls')),
    
]

users/urls.py
from django.urls import path, include

from users.views import register, activate

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),

]

retirement_calculator/forms.py
from django import forms


class Calculator(forms.Form):
    age = forms.DecimalField(min_value=15, max_value=80)
    age_retirement = forms.DecimalField(min_value=18, max_value=80)
    monthly_save = forms.FloatField()
    saved_now = forms.FloatField()
    income_spent = forms.FloatField()

templates/calculator.html
{% load static %}
<html lang="en">
<head>
    <title>Retirement calculator</title>
    <link rel="icon" href="data:,">
    <script src="https://kit.fontawesome.com/34f40f3751.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href='{% static "css/style_noutati.css" %}'>

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }


        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="text"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        a, a:hover, a:focus, a:active {
            text-decoration: none;
            color: inherit;
        }

    </style>
</head>

<body>
<main class="form-signin">
    <h3>Hello there!</h3>
    <br>
    <h3>Find out how much more you need to save for your retirement using the calculator below.</h3>
    <form method="post" action="">
        {% csrf_token %}
        <label for="id_age">How old are you?</label><br>
        <small style="font-size: 12px">Min:15, Max:80, No negative numbers</small>

        <div class="form-floating" style="margin-bottom: 10px">
            <input name="age" type="number" class="form-control" id="id_age" required>
        </div>
        <label for="id_age_retirement">At what age do you want to retire?</label><br>
        <small style="font-size: 12px">Min:15, Max:80, No negative numbers</small>

        <div class="form-floating" style="margin-bottom: 10px">
            <input name="age_retirement" type="number" class="form-control" id="id_age_retirement"
                   required>
        </div>
        <label for="id_monthly_save">How much do you save per month?</label>
        <div class="form-floating" style="margin-bottom: 10px">
            <input name="monthly_save" type="number" class="form-control" id="id_monthly_save"
                   placeholder="How much do you save per month?" required>
        </div>

        <label for="id_saved_now">How much have you saved until now?</label><br>
        <small style="font-size: 12px">If you don't have savings write 0.</small>

        <div class="form-floating" style="margin-bottom: 10px">
            <input name="saved_now" type="number" class="form-control" id="id_saved_now"
                   placeholder="How much have you saved until now?" required>
        </div>

        <label for="id_income_spent">How much do you spend per month?</label>
        <div class="form-floating" style="margin-bottom: 10px">
            <input name="income_spent" type="number" class="form-control" id="id_income_spent"
                   placeholder="How much do you spend per month?" required>
        </div>

        <input class="btn btn-dark" name="submit" type="submit" value="Calculate"
               style="background-color: #454545; position: relative; left: 3px; width: 146px; bottom: 5px">

        <button class="btn btn-dark"
                style="background-color: #454545; position: relative; left: 3px; width: 146px; bottom: 5px"><a
                href="{% url 'index' %}"> Back to home</a></button>
    </form>
</main>
</body>
</html>

templates/calculator_results.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Retirement calculator</title>
    <link rel="icon" href="data:,">
    <script src="https://kit.fontawesome.com/34f40f3751.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <style>
        body {
            height: 100%;
        }

        body {
            align-items: center;
            padding-top: 50px;
            padding-bottom: 20px;
            background-color: #f5f5f5;
        }


        .post-left {
            width: 30%;
            background-color: #009879;
            color: white;
            padding: 3em;
            margin: auto;
        }

        .post-left_title {
            font-size: 2em;
            font-weight: 700;
        }

        .post-left_title_sub {
            font-size: 1.5em;
            font-weight: 300;
            margin-top: 0.40em;
        }

        a, a:hover, a:focus, a:active {
            text-decoration: none;
            color: inherit;
        }

    </style>
</head>
<body>
<div class="post">
    <div class="post-left">
        <div class="post-left_title">Your retirement:</div>
        <div class="post-left_title_sub">Until retirement you have to work: <u>{{ until_retirement }} years</u></div>
        <div class="post-left_title_sub">Years spent in retirement: <u>{{ years_in_retirement }} years</u></div>
        <div class="post-left_title_sub">You save this much per year: <u>{{ year_save }}</u></div>
        <div class="post-left_title_sub">You should save at least <u>{{ inflation_ajusted_monthly_save }}</u> per month.
        </div>
        <div class="post-left_title_sub">Your spent income will increase close to
            <u>{{ inflation_ajusted_income_spent }}</u>
            because of inflation.
        </div>
        <div class="post-left_title_sub">You will have saved this much until retirement
            <u>{{ saved_until_retirement }}</u> but
            you will need <u>{{ difference }}</u>
            more currency to retire with no problems.
        </div>
        <small>How did we get the results?</small>
        <br>
        <small>Life expectation is default 80 years.
            The inflation is default 3%.
        </small>
        <br>
        <small>
            Please note this is a general and simplistic calculator
            as for more accurate results there are more variables to be known.</small>
    </div>
</div>
<button class="btn btn-dark" style="background-color: #454545; margin-top:20px; margin-left: 900px;"><a
        href="{% url 'index' %}">Back to home</a></button>

</body>
</html>

templates/crypto.html
{% load static %}
<html lang="en">

<head>
    <title>NFinance</title>
    <link rel="icon" href="data:,">
    <script src="https://kit.fontawesome.com/34f40f3751.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href='{% static "css/style_noutati.css" %}'>

    <style>
        * {
            box-sizing: border-box;
        }

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            background-color: #454545;
            overflow: hidden;
            height: 49px;
        }

        li {
            float: left;

        }

        li:last-child {
            border-right: none;
        }

        li a {
            font-family: -apple-system, "BlinkMacSystemFont", "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Open Sans", "Helvetica Neue", "Icons16", sans-serif;
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            background-color: #454545;
            text-decoration: none;
        }

        a {
            text-decoration: none;
        }

        li a:hover:not(.active) {
            background-color: #111;
        }

        .active {
            background-color: #111;
        }

    </style>
</head>

<body>
<div class="menup">
    <ul>
        <a href="{% url 'index' %}">
            <li><img src={% static "img/logo2.png" %} alt="logo" style="padding: 10px 16px; display: block;"></li>
        </a>
        <li><a href="{% url 'index' %}">News</a></li>
        <li><a class="active" href="">Crypto</a></li>
        <li><a href="{% url 'tickers' %}">Tickers</a></li>
        <li><a href="{% url 'personal' %}">Personal Finance</a></li>
        <li><a href="{% url 'calculator' %}" style="padding-top: 19px"><i class="fas fa-calculator"></i></a></li>

        {% if user.is_authenticated %}
            <li style="float: right"><a href="{% url 'subscribe' %}">Subscribe</a></li>
            <li style="float: right"><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
            <li style="float: right"><a href="{% url 'register' %}"> Sign Up</a></li>
            <li style="float: right"><a href="{% url 'login' %}"> Login</a></li>

        {% endif %}
        <li style="width: 800px">
            <form method="POST" action="{% url 'filter' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="wraps">
                    <div class="search">
                        <input id="filter" type="text" class="searchTerm" placeholder="Search for news.." name="filter"
                               required>
                        <button type="submit" class="searchButton">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </li>
    </ul>
</div>
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-tickers.js" async>
        {
            "symbols"
        :
            [
                {
                    "proName": "FOREXCOM:SPXUSD",
                    "title": "S&P 500"
                },
                {
                    "proName": "FOREXCOM:NSXUSD",
                    "title": "Nasdaq 100"
                },
                {
                    "proName": "FX_IDC:EURUSD",
                    "title": "EUR/USD"
                },
                {
                    "proName": "BITSTAMP:BTCUSD",
                    "title": "BTC/USD"
                },
                {
                    "proName": "BITSTAMP:ETHUSD",
                    "title": "ETH/USD"
                }
            ],
                "colorTheme"
        :
            "light",
                "isTransparent"
        :
            true,
                "showSymbolLogo"
        :
            false,
                "locale"
        :
            "en"
        }
    </script>
</div>
<!-- TradingView Widget END -->
<br>
<br>
<div class="row">
    <div class="wrapper">
        {% for object in crypto_news %}
            <div class="cards">
                <a href="{{ object.url }}" target="_blank"><img alt="{{ object.title }}" src="{{ object.head_img }}"
                                                                style="padding: 10px 20px 20px 0"
                                                                width="300px"
                                                                height="auto"></a>
                <a href="{{ object.url }}" target="_blank"><h3 class="subtitlu"
                                                               style="margin: 0px">{{ object.title }}</h3></a>
                <p style="font-size: 10px">{{ object.datetime }}</p>

                <p>{{ object.start_paragraph }}</p>
            </div>
        {% endfor %}
    </div>
</div>
</body>

<div class="footer">
    <div>
        <a href="https://www.facebook.com/sorinbland" target="blank"><i class="fab fa-facebook-square"
                                                                        style="font-size: 36px;color: rgb(255, 255, 255);"></i></a>
        <a href="https://www.instagram.com/hapcius/" target="blank"><i class="fab fa-instagram-square"
                                                                       style="font-size: 36px;color: rgb(255, 255, 255);"></i></a>
        <a href="https://www.reddit.com/user/Ciucku" target="blank"><i class="fab fa-reddit-square"
                                                                       style="font-size: 36px;color: rgb(255, 255, 255);"></i></a>
        <br>
        <p>Made with <i class="fas fa-heart" style="color: red"></i> by Sorin Bland</p>
    </div>
</div>
</html>

templates/filter.html
{% load static %}
<html lang="en">

<head>
    <title>NFinance</title>
    <link rel="icon" href="data:,">
    <script src="https://kit.fontawesome.com/34f40f3751.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href='{% static "css/style_noutati.css" %}'>
    <style>
        * {
            box-sizing: border-box;
        }

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            background-color: #454545;
            overflow: hidden;
            height: 49px;
        }

        li {
            float: left;

        }

        li:last-child {
            border-right: none;
        }

        li a {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            background-color: #454545;
            text-decoration: none;
        }

        a {
            text-decoration: none;
        }

        li a:hover:not(.active) {
            background-color: #111;
        }

        .active {
            background-color: #111;
        }

    </style>
</head>

<body>
{#<h1 class="header">NFinance</h1>#}
<div class="menup">
    <ul>
        <a href="{% url 'index' %}">
            <li><img src={% static "img/logo2.png" %} alt="logo" style="padding: 10px 16px; display: block;"></li>
        </a>
        <li><a href="/">News</a></li>
        <li><a href="{% url 'crypto' %}">Crypto</a></li>
        <li><a href="{% url 'tickers' %}">Tickers</a></li>
        <li><a href="{% url 'personal' %}">Personal Finance</a></li>
        <li><a href="{% url 'calculator' %}" style="padding-top: 19px"><i class="fas fa-calculator"></i></a></li>

        {% if user.is_authenticated %}
            <li style="float: right"><a href="{% url 'subscribe' %}">Subscribe</a></li>
            <li style="float: right"><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}

            <li style="float: right"><a href="{% url 'register' %}"> Sign Up</a></li>
            <li style="float: right"><a href="{% url 'login' %}"> Login</a></li>

        {% endif %}
        <li style="width: 800px">
            <form method="POST" action="">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="wraps">
                    <div class="search">
                        <input id="filter" type="text" class="searchTerm" placeholder="Search for news.." name="filter"
                               required>
                        <button type="submit" class="searchButton">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </li>
    </ul>
</div>
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-tickers.js" async>
        {
            "symbols"
        :
            [
                {
                    "proName": "FOREXCOM:SPXUSD",
                    "title": "S&P 500"
                },
                {
                    "proName": "FOREXCOM:NSXUSD",
                    "title": "Nasdaq 100"
                },
                {
                    "proName": "FX_IDC:EURUSD",
                    "title": "EUR/USD"
                },
                {
                    "proName": "BITSTAMP:BTCUSD",
                    "title": "BTC/USD"
                },
                {
                    "proName": "BITSTAMP:ETHUSD",
                    "title": "ETH/USD"
                }
            ],
                "colorTheme"
        :
            "light",
                "isTransparent"
        :
            true,
                "showSymbolLogo"
        :
            false,
                "locale"
        :
            "en"
        }
    </script>
</div>
<!-- TradingView Widget END -->
<br>
<br>
<div class="row">
    <div class="wrapper">
        {% for object in articles_filtered %}
            <div class="cards">
                <a href="{{ object.url }}" target="_blank"><img alt="{{ object.title }}" src="{{ object.head_img }}"
                                                                style="padding: 10px 20px 20px 0"
                                                                width="300px"
                                                                height="auto"></a>
                <a href="{{ object.url }}" target="_blank"><h3 class="subtitlu"
                                                               style="margin: 0px">{{ object.title }}</h3></a>
                <p style="font-size: 10px">{{ object.datetime }}</p>

                <p>{{ object.start_paragraph }}</p>
            </div>
        {% endfor %}
    </div>
</div>
</body>

<div class="footer">
<div>
        <a href="https://www.facebook.com/sorinbland" target="blank"><i class="fab fa-facebook-square"
                                                                        style="font-size: 36px;color: rgb(255, 255, 255);"></i></a>
        <a href="https://www.instagram.com/hapcius/" target="blank"><i class="fab fa-instagram-square"
                                                                       style="font-size: 36px;color: rgb(255, 255, 255);"></i></a>
        <a href="https://www.reddit.com/user/Ciucku" target="blank"><i class="fab fa-reddit-square"
                                                                       style="font-size: 36px;color: rgb(255, 255, 255);"></i></a>
        <br>
        <p>Made with <i class="fas fa-heart" style="color: red"></i> by Sorin Bland</p>
    </div>
</div>
</html>

templates/index.html
{% load static %}
<html lang="en">

<head>
    <title>NFinance</title>
    <link rel="icon" href="data:,">
    <script src="https://kit.fontawesome.com/34f40f3751.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href='{% static "css/style_noutati.css" %}'>

    <style>
        * {
            box-sizing: border-box;
        }

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            background-color: #454545;
            overflow: hidden;
            height: 49px;
        }

        li {
            float: left;

        }

        li:last-child {
            border-right: none;
        }

        li a {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            background-color: #454545;
            text-decoration: none;
        }

        li a:hover:not(.active) {
            background-color: #111;
        }

        .active {
            background-color: #111;
        }

        a {
            text-decoration: none;
        }

    </style>
</head>

<body>

<div class="menup">
    <ul>
        <a href="/">
            <li><img src={% static "img/logo2.png" %} alt="logo" style="padding: 10px 16px; display: block; top: 2px">
            </li>
        </a>
        <li><a class="active" href="">News</a></li>
        <li><a href="{% url 'crypto' %}">Crypto</a></li>
        <li><a href="{% url 'tickers' %}">Tickers</a></li>
        <li><a href="{% url 'personal' %}">Personal Finance</a></li>
        <li><a href="{% url 'calculator' %}" style="padding-top: 19px"><i class="fas fa-calculator"></i></a></li>
        {% if user.is_authenticated %}
            <li style="float: right"><a href="{% url 'subscribe' %}">Subscribe</a></li>
            <li style="float: right"><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
            <li style="float: right"><a href="{% url 'register' %}"> Sign Up</a></li>
            <li style="float: right"><a href="{% url 'login' %}"> Login</a></li>

        {% endif %}

        <li style="width: 800px">
            <form method="POST" action="{% url 'filter' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="wraps">
                    <div class="search">
                        <input id="filter" type="text" class="searchTerm" placeholder="Search for news.." name="filter"
                               required>
                        <button type="submit" class="searchButton">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </li>
    </ul>
</div>

<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-tickers.js" async>
        {
            "symbols"
        :
            [
                {
                    "proName": "FOREXCOM:SPXUSD",
                    "title": "S&P 500"
                },
                {
                    "proName": "FOREXCOM:NSXUSD",
                    "title": "Nasdaq 100"
                },
                {
                    "proName": "FX_IDC:EURUSD",
                    "title": "EUR/USD"
                },
                {
                    "proName": "BITSTAMP:BTCUSD",
                    "title": "BTC/USD"
                },
                {
                    "proName": "BITSTAMP:ETHUSD",
                    "title": "ETH/USD"
                }
            ],
                "colorTheme"
        :
            "light",
                "isTransparent"
        :
            true,
                "showSymbolLogo"
        :
            false,
                "locale"
        :
            "en"
        }

    </script>
</div>
<!-- TradingView Widget END -->


<div class="row">
    <div class="wrapper">
        {% for object in object_list %}
            <div class="cards">
                <a href="{{ object.url }}" target="_blank"><img alt="{{ object.title }}" src="{{ object.head_img }}"
                                                                style="padding: 10px 20px 20px 0"
                                                                width="300px"
                                                                height="auto"></a>
                <a href="{{ object.url }}" target="_blank"><h3 class="subtitlu"
                                                               style="margin: 0px">{{ object.title }}</h3></a>
                <p style="font-size: 10px">{{ object.datetime }}</p>

                <p>{{ object.start_paragraph }}</p>
            </div>
        {% endfor %}
    </div>
</div>

</body>

<div class="footer">
<div>
        <a href="https://www.facebook.com/sorinbland" target="blank"><i class="fab fa-facebook-square"
                                                                        style="font-size: 36px;color: rgb(255, 255, 255);"></i></a>
        <a href="https://www.instagram.com/hapcius/" target="blank"><i class="fab fa-instagram-square"
                                                                       style="font-size: 36px;color: rgb(255, 255, 255);"></i></a>
        <a href="https://www.reddit.com/user/Ciucku" target="blank"><i class="fab fa-reddit-square"
                                                                       style="font-size: 36px;color: rgb(255, 255, 255);"></i></a>
        <br>
        <p>Made with <i class="fas fa-heart" style="color: red"></i> by Sorin Bland</p>
    </div>
</div>
</html>

templates/personal_finance.html
{% load static %}
<html lang="en">

<head>
    <title>NFinance</title>
    <link rel="icon" href="data:,">
    <script src="https://kit.fontawesome.com/34f40f3751.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href='{% static "css/style_noutati.css" %}'>

    <style>
        * {
            box-sizing: border-box;
        }

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            background-color: #454545;
            overflow: hidden;
            height: 49px;
        }

        li {
            float: left;

        }

        li:last-child {
            border-right: none;
        }

        li a {
            font-family: -apple-system, "BlinkMacSystemFont", "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Open Sans", "Helvetica Neue", "Icons16", sans-serif;
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            background-color: #454545;
            text-decoration: none;
        }

        a {
            text-decoration: none;
        }

        li a:hover:not(.active) {
            background-color: #111;
        }

        .active {
            background-color: #111;
        }

    </style>
</head>

<body>
<div class="menup">
    <ul>
        <a href="{% url 'index' %}">
            <li><img src={% static "img/logo2.png" %} alt="logo" style="padding: 10px 16px; display: block;"></li>
        </a>
        <li><a href="{% url 'index' %}">News</a></li>
        <li><a href="{% url 'crypto' %}">Crypto</a></li>
        <li><a href="{% url 'tickers' %}">Tickers</a></li>
        <li><a class="active" href="">Personal Finance</a></li>
        <li><a href="{% url 'calculator' %}" style="padding-top: 19px"><i class="fas fa-calculator"></i></a></li>

        {% if user.is_authenticated %}
            <li style="float: right"><a href="{% url 'subscribe' %}">Subscribe</a></li>
            <li style="float: right"><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
            <li style="float: right"><a href="{% url 'register' %}">Sign Up</a></li>
            <li style="float: right"><a href="{% url 'login' %}">Login</a></li>
        {% endif %}

        <li style="width: 800px">
            <form method="POST" action="{% url 'filter' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="wraps">
                    <div class="search">
                        <input id="filter" type="text" class="searchTerm" placeholder="Search for news.." name="filter"
                               required>
                        <button type="submit" class="searchButton">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </li>
    </ul>
</div>
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-tickers.js" async>
        {
            "symbols"
        :
            [
                {
                    "proName": "FOREXCOM:SPXUSD",
                    "title": "S&P 500"
                },
                {
                    "proName": "FOREXCOM:NSXUSD",
                    "title": "Nasdaq 100"
                },
                {
                    "proName": "FX_IDC:EURUSD",
                    "title": "EUR/USD"
                },
                {
                    "proName": "BITSTAMP:BTCUSD",
                    "title": "BTC/USD"
                },
                {
                    "proName": "BITSTAMP:ETHUSD",
                    "title": "ETH/USD"
                }
            ],
                "colorTheme"
        :
            "light",
                "isTransparent"
        :
            true,
                "showSymbolLogo"
        :
            false,
                "locale"
        :
            "en"
        }
    </script>
</div>
<!-- TradingView Widget END -->
<br>
<br>
<div class="row">
    <div class="wrapper">
        {% for object in personal_news %}
            <div class="cards">
                <a href="{{ object.url }}" target="_blank"><img alt="{{ object.title }}" src="{{ object.head_img }}"
                                                                style="padding: 10px 20px 20px 0"
                                                                width="300px"
                                                                height="auto"></a>
                <a href="{{ object.url }}" target="_blank"><h3 class="subtitlu"
                                                               style="margin: 0px">{{ object.title }}</h3></a>
                <p style="font-size: 10px">{{ object.datetime }}</p>

                <p>{{ object.start_paragraph }}</p>
            </div>
        {% endfor %}
    </div>
</div>
</body>

<div class="footer">
    <div>
        <a href="https://www.facebook.com/sorinbland" target="blank"><i class="fab fa-facebook-square"
                                                                        style="font-size: 36px;color: rgb(255, 255, 255);"></i></a>
        <a href="https://www.instagram.com/hapcius/" target="blank"><i class="fab fa-instagram-square"
                                                                       style="font-size: 36px;color: rgb(255, 255, 255);"></i></a>
        <a href="https://www.reddit.com/user/Ciucku" target="blank"><i class="fab fa-reddit-square"
                                                                       style="font-size: 36px;color: rgb(255, 255, 255);"></i></a>
        <br>
        <p>Made with <i class="fas fa-heart" style="color: red"></i> by Sorin Bland</p>
    </div>
</div>
</html>