Finance_news_aggregator/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("finance_app.urls")),
    path("users/", include("users.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('subscribe/', include('subscribe.urls')),
    path('retirement-calculator/', include('retirement_calculator.urls')),
    
]

subscribe/urls.py
from django.urls import path

from subscribe.views import subscribe, subscribe_mails, unsubscribe

urlpatterns = [
    path('', subscribe, name='subscribe'),
    path('subscribe-email/', subscribe_mails, name='subscribe_mails'),
    path("unsubscribe/", unsubscribe, name="unsubscribe"),

]

users/urls.py
from django.urls import path, include

from users.views import register, activate

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),

]

subscribe/models.py
from django.db import models


# Create your models here.


class SubEmails(models.Model):
    email = models.EmailField(unique=True)
    uuid = models.CharField(max_length=9999, null=True, blank=True)

    def __str__(self):
        return self.email

subscribe/forms.py
from django import forms


class Subscribe(forms.Form):
    email = forms.EmailField()

    def __str__(self):
        return self.email

subscribe/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, EmailMessage
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from Finance_news_aggregator.settings import EMAIL_HOST_USER
from finance_app.models import Headline
from subscribe import forms
import smtplib
from subscribe.models import SubEmails
import uuid


# Emails that are sent
def subscribe_mails():
    mail_subject = "Your news!"
    headlines = Headline.objects.all()[::-1]
    message = render_to_string('subscribe/subscribe_mail_sent.html', {'headlines': headlines[:3]})
    mails = SubEmails.objects.all()
    list_mails = []
    for mail in mails:
        if mail.email not in list_mails:
            list_mails.append(mail.email)
    email = EmailMessage(
        mail_subject, message, to=list_mails
    )
    print('Sending email')
    email.send()
    print('Email sent')


# Subscribe method + welcome message
def subscribe(request):
    sub = forms.Subscribe()
    if request.method == 'POST' and 'subscribe' in request.POST:
        try:
            new_mail = SubEmails()
            sub = forms.Subscribe(request.POST)
            subject = 'Welcome to NFinance!'
            message = 'We promise to not spam you! ' \
                      'You will get three time a month the most recent news!'
            to_email = str(sub['email'].value())
            new_mail.email = to_email

            if sub.is_valid():
                new_mail.uuid = uuid.uuid4()
                new_mail.save()
            send_mail(subject,
                      message, EMAIL_HOST_USER, [to_email], fail_silently=False)
            return render(request, 'subscribe/success.html', {'to_email': to_email})

        except IntegrityError:
            return render(request, 'subscribe/subscribe_already_subscribed.html', {'form': sub})

        except smtplib.SMTPRecipientsRefused:
            return render(request, 'subscribe/subscribe_mail_error.html', {'form': sub})

    return render(request, 'subscribe/subscribe.html', {'form': sub})


# Unsubscribe method
def unsubscribe(request):
    form = forms.Subscribe(request.POST)
    if form.is_valid():
        user_mail = str(form['email'].value())
        database_email = str(request.user.email)
        if user_mail == database_email:
            SubEmails.objects.filter(email=user_mail).delete()
            return render(request, "subscribe/unsubscribed.html")
        return HttpResponse("We don't recognize this email!")
    else:
        return render(request, "subscribe/unsubscribe.html", {"form": form})

templates/subscribe/subscribe.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="icon" href="data:,">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Subscribe</title>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }


        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="text"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        a, a:hover, a:focus, a:active {
            text-decoration: none;
            color: inherit;
        }
    </style>

</head>

<body class="text-center">
<main class="form-signin">
<h2 style="margin-bottom: 20px">Get news right in your mailbox!</h2>
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-floating" style="margin-bottom: 10px">
            <input name="email" type="text" class="form-control" id="id_email" placeholder="Email" required>
            <label for="id_email">Email</label>
            {% for err in form.email.errors %}
                <small>{{ err }}</small>
            {% endfor %}
        </div>
        <input class="w-100 btn btn-lg btn-primary" name="subscribe" type="submit" value="Subscribe"
               style="background-color: #454545">
    </form>

</main>
</body>
</html>

templates/subscribe/subscribe_already_subscribed.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Subscribe</title>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        a, a:hover, a:focus, a:active {
            text-decoration: none;
            color: inherit;
        }
         .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }
    </style>

</head>

<body class="text-center">
<main class="form-signin">
<h2 style="margin-bottom: 20px">You are already subscribed!</h2>
    <button class="w-100 btn btn-lg btn-primary"
            style="background-color: #454545"><a href="{% url 'index' %}"> Take me home</a></button>

</main>
</body>
</html>

templates/subscribe/subscribe_mail_error.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Subscribe</title>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }


        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="text"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        a, a:hover, a:focus, a:active {
            text-decoration: none;
            color: inherit;
        }
    </style>

</head>

<body class="text-center">
<main class="form-signin">
<h2 style="margin-bottom: 20px">Wrong email format! </h2>
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-floating" style="margin-bottom: 10px">
            <input name="email" type="text" class="form-control" id="id_email" placeholder="Email" required>
            <label for="id_email">Email</label>
            {% for err in form.email.errors %}
                <small>{{ err }}</small>
            {% endfor %}
        </div>
        <input class="w-100 btn btn-lg btn-primary" name="subscribe" type="submit" value="Subscribe"
               style="background-color: #454545">
    </form>

</main>
</body>
</html>

templates/subscribe/subscribe_mail_sent.html
The most recent news are here:
{% for object in headlines %}

    {{ object.title }}
    {{ object.url }}

{% endfor %}

If you wish to unsubscribe, click below!
http://127.0.0.1:8000/subscribe/unsubscribe

Hope you enjoy, have a nice day!
NFinance Team!

templates/subscribe/success.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Subscribe</title>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        a, a:hover, a:focus, a:active {
            text-decoration: none;
            color: inherit;
        }
         .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }
    </style>

</head>

<body class="text-center">
<main class="form-signin">
<h2 style="margin-bottom: 20px">You have succesfully subscribed!</h2>
    <button class="w-100 btn btn-lg btn-primary"
            style="background-color: #454545"><a href="{% url 'index' %}"> Take me home</a></button>

</main>
</body>
</html>

templates/subscribe/unsubscribe.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="icon" href="data:,">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Unsubscribe</title>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }


        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="text"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        a, a:hover, a:focus, a:active {
            text-decoration: none;
            color: inherit;
        }
    </style>

</head>

<body class="text-center">
<main class="form-signin">
<h2 style="margin-bottom: 20px">Enter your email to unsubscribe!</h2>
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-floating" style="margin-bottom: 10px">
            <input name="email" type="text" class="form-control" id="id_email" placeholder="Email" required>
            <label for="id_email">Email</label>
            {% for err in form.email.errors %}
                <small>{{ err }}</small>
            {% endfor %}
        </div>
        <input class="w-100 btn btn-lg btn-primary" name="unsubscribe" type="submit" value="Unsubscribe"
               style="background-color: #454545">
    </form>

</main>
</body>
</html>

templates/subscribe/unsubscribed.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Unsubscribe</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href='{% static "css/style_noutati.css" %}'>
    <style>

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }
    </style>
</head>
<body>
<main class="form-signin">
    <h3>You have unsubscribed! We hope to see you soon!</h3>

</main>

</body>
</html>